### ISSUE TITLE
TODO before version 1.0

### ISSUE THREAD

**Issue by mpizenberg** [mpizenberg/elm-cardano#2]
There are 3 key aspects for a Cardano offchain library in Elm.

1. Wallet connection with CIP30 and CIP45
2. Building, submitting, watching transactions
3. A simulation environment to help end-to-end testing of aiken contracts

## Wallet connection with CIP30 and CIP45

- [x] Connect to a [CIP30](https://cips.cardano.org/cips/cip30/) enabled wallet
- [ ] Connect to a [CIP45](https://github.com/cardano-foundation/CIPs/pull/395) enabled wallet (eternl)
- [x] Hardware wallet support https://github.com/cardano-foundation/CIPs/blob/master/CIP-0021/README.md

## Building, submitting, watching transactions

- [x] Define the types and CBOR codecs to build a transaction: #1 
- [x] Define an API to create transactions (inputs, outputs, destinations, validators, utxo selection strategy, ...)
- [ ] Being able to submit a transaction with ease (local node, remote node, blockfrost, txpipe, ...)
- [ ] Being able to request information easily (wallet utxos, watch submission status, mempool, ...)

## Simulation environment for end-to-end testing

- [x] Check phase-2 by being able to run a transaction in a sandbox, via aiken simulation
- [ ] Check phase-1 by providing context
- [ ] Ability to replay with time-travel debugging

**Comment by mpizenberg** [comment]
Goal-oriented roadmap:


- Wallets interactions
  - CIP30 support
  - CIP45 support
  - Explore improvements for Dapp-Wallet interactions
    - per-open-dapp personas
    - per-open-dapp account
    - per-open-dapp multi-account

- Community Tooling
  - Transaction Explorer web app
    - Educative (links to relevant sources, ...)
    - Simple (comprehensible tx overview, ...)
    - Powerful / Complete (inspect all parts, convert formats, ...)
  - Interactive transaction Builder web app
    - Suite of common Tx types (send to, mint, multi-sig, ...)
    - Steps-by-steps guided interactive builder for custom Tx

- Dapp examples
  - Equivalent to Radix Gumball Club https://gumball-club.radixdlt.com/
