### ISSUE TITLE
Detailed still TODO for great Tx building

### ISSUE THREAD

**Issue by mpizenberg** [mpizenberg/elm-cardano#46]
This is an almost exhaustive (trying) list of things still to do if we want to have the best Tx building experience for offchain Cardano frameworks. Not everything has the same priority.

## Critical

- [x] Finalize the elm-cardano binary story for the web (not Node) #41 #49 
- [x] Implement hashing for auxiliary data hash and script data hash #39  #51 #53
- [x] Adjust fee computation to take into account script reference fees #38 
- [x] Rewrite the Cardano module documentation #48 
- [x] Finalize CIP30 #35 
- [x] Tx builder working for mainnet
- [x] Tx builder working for testnet (preprod / preview)
- [x] Can create addresses from Hex
- [ ] Have at least one API provider
- [x] Hosted documentation

## Important

- [x] Can create addresses from Bech32
- [x] Redo a collateral-specific coin selection algo, compatible with cip40 #87 
- [ ] Add support for blueprint handling for smart contracts using elm-codegen (https://github.com/mdgriffith/elm-codegen)
- [x] Rename `fromStringUnchecked` into `fromHexUnchecked`, same for `fromString`
- [ ] Add ability to use network parameters for fee computation
- [ ] Add ability to provide coinsPerUtxoByte parameter for minAda computation
- [x] Find a way to use elm-cardano script evaluation in tests (elm-cardano binary for Node) #49 
- [ ] Support fees from script addresses in Tx building
- [ ] Handle plutus Data in witness
- [x] Add intents for certificates #72 
- [x] Add intents for voting #72 
- [x] Add intents for proposals #72 
- [x] Make cbor encoding compatible with hardware wallets (cip21) #52 
- [x] Cleanup and document the Gov module #48 
- [x] Remove the Transaction.Builder.elm module #48 
- [x] Flatten the AuxiliaryData modules directly in Cardano namespace #48 
- [x] Remove the Maybe for the Tx body fee #70 
- [x] When Natural is 2^53 < N < 2^64, it should be CBOR-encoded as 64-bit instead of BigInt #23
- [x] Improve error handling (error messages) of CIP30 issues of some wallets #71 

## Later

- [ ] Improve coin selection in Tx building to automatically remove fees from returned ada without need for a dedicated new utxo input
- [ ] Add CIP 45 support (webrtc dapp-wallet bridge)
- [ ] Add CIP 95 support (Gov-related dapp-wallet bridge)
- [ ] Add control over max input count in coin selection in Tx building
- [ ] Other general improvements in coin selection algorithms
- [x] Add a test for collateral selection error #87 
- [ ] If there is enough free ada in the change, make a collateral-viable utxo in outputs
- [ ] Actual handling of pointer addresses
- [ ] Rework CBOR decoders to be able to fail with error messages
- [ ] Rework Bytes for safe usage, deal with current escape hatches
- [ ] Remove all usage of Debug to be able to publish package v1.0.0
